[package]
edition      = "2024"
name         = "Crusty"
rust-version = "1.97"
version      = "0.1.0"

[[bin]]
name = "Crusty"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "1.2", features = ["esp32", "unstable"] }
embedded-hal = "1.0.0"



esp-bootloader-esp-idf = { version = "^0.6.0", features = ["esp32"] }

critical-section = "1.2.0"
esp-println = { version = "0.18.0", features = ["esp32"] }
esp-backtrace = { version = "0.20.0", features = ["esp32", "println"] }
embedded-io = "0.7.1"
ssd1306 = { version = "0.10.0", features = ["async"] }
embedded-graphics = "0.8.1"
defmt = "1.1.1"
embassy-executor = "0.10.0"
embassy-time = "0.5.1"
esp-rtos = { version = "0.4.0", features = ["embassy", "esp32"] }
esp-rom-sys = "0.1.5"
xtensa-lx = "0.13.0"
nb = "1.1.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
